FROM node:22.19.0-alpine AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
RUN apk add --no-cache libc6-compat openssl

FROM base AS dev
ARG APP
WORKDIR /app


# Expose Nextjs dev server ports
EXPOSE 3000

# Start development server
WORKDIR /app/apps/frontend
CMD ["pnpm", "dev"]
