import type { Metadata } from "next";
import { Geist, IBM_Plex_Mono } from "next/font/google";
import "@/styles/styles.css";
import { Toaster } from "sonner";
import { QueryProviders, SessionProviders } from "@/providers";

const geistSans = Geist({
  variable: "--font-sans",
  subsets: ["latin"],
});

const ibmPlexMono = IBM_Plex_Mono({
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${ibmPlexMono.variable} antialiased`}
      >
        <QueryProviders>
          <SessionProviders>
            {children}
            <Toaster position="top-center" richColors />
          </SessionProviders>
        </QueryProviders>
      </body>
    </html>
  );
}
