import { AppProviders } from "@/providers";
import "@/styles/global.css";
import type { Metadata } from "next";
import { Geist, IBM_Plex_Mono } from "next/font/google";
import { Toaster } from "sonner";

const geistSans = Geist({
	variable: "--font-sans",
	subsets: ["latin"],
});

const ibmPlexMono = IBM_Plex_Mono({
	weight: ["100", "200", "300", "400", "500", "600", "700"],
	variable: "--font-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Library",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${ibmPlexMono.variable} antialiased`}
			>
				<AppProviders>
					{children}
					<Toaster position="top-center" richColors />
				</AppProviders>
			</body>
		</html>
	);
}
